sudo: required
language: bash
services:
  - docker

script:
  # at least run a syntax check for the Travis scripts
  - bash -n storage-ng-travis-cpp
  - bash -n storage-ng-travis-ruby
  - docker build -t storage-ng-image .
